@echo off
title JARVIS Installer
color 0B
:: ============================================================
::  J.A.R.V.I.S. - Just A Rather Very Intelligent System
::  One-File Installer  |  github.com/mercy1234544/jarvis-ai
:: ============================================================

:: Check if running as Administrator — if not, re-launch elevated
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo  Requesting administrator privileges...
    powershell -Command "Start-Process cmd -ArgumentList '/c \"%~f0\"' -Verb RunAs"
    exit /b
)

set "PS=%TEMP%\jarvis_%RANDOM%.ps1"
setlocal DisableDelayedExpansion

echo $ErrorActionPreference = 'Stop'>>"%PS%"
echo $ProgressPreference = 'SilentlyContinue'>>"%PS%"
echo $Host.UI.RawUI.WindowTitle = 'JARVIS Installer'>>"%PS%"
echo.>>"%PS%"
echo $INSTALL_DIR = Join-Path $env:USERPROFILE 'JARVIS'>>"%PS%"
echo $REPO        = 'https://github.com/mercy1234544/jarvis-ai.git'>>"%PS%"
echo $NODE_MSI    = 'https://nodejs.org/dist/v20.11.1/node-v20.11.1-x64.msi'>>"%PS%"
echo $GIT_URL     = 'https://github.com/git-for-windows/git/releases/download/v2.44.0.windows.1/Git-2.44.0-64-bit.exe'>>"%PS%"
echo.>>"%PS%"
echo function Banner {>>"%PS%"
echo     Clear-Host>>"%PS%"
echo     Write-Host '  ============================================================' -ForegroundColor Cyan>>"%PS%"
echo     Write-Host '   J.A.R.V.I.S. -  Just A Rather Very Intelligent System' -ForegroundColor White>>"%PS%"
echo     Write-Host '   One-File Installer' -ForegroundColor Cyan>>"%PS%"
echo     Write-Host '  ============================================================' -ForegroundColor Cyan>>"%PS%"
echo     Write-Host ''>>"%PS%"
echo }>>"%PS%"
echo function Step   { param($n,$m) Write-Host "  [$n/6] $m" -ForegroundColor Cyan }>>"%PS%"
echo function OK     { param($m) Write-Host "  [OK] $m" -ForegroundColor Green }>>"%PS%"
echo function WARN   { param($m) Write-Host "  [!!] $m" -ForegroundColor Yellow }>>"%PS%"
echo function INFO   { param($m) Write-Host "       $m" -ForegroundColor Gray }>>"%PS%"
echo function FAIL   { param($m) Write-Host "  [XX] $m" -ForegroundColor Red; Write-Host ''; Write-Host '  Press Enter to exit...' -ForegroundColor DarkGray; Read-Host; exit 1 }>>"%PS%"
echo.>>"%PS%"
echo Banner>>"%PS%"
echo.>>"%PS%"
echo # ── STEP 1: Git ──────────────────────────────────────────────────────────>>"%PS%"
echo Step 1 'Checking for Git...'>>"%PS%"
echo $git = Get-Command git -ErrorAction SilentlyContinue>>"%PS%"
echo if (-not $git) {>>"%PS%"
echo     WARN 'Git not found. Downloading Git for Windows (~50 MB)...'>>"%PS%"
echo     $tmp = Join-Path $env:TEMP 'git-setup.exe'>>"%PS%"
echo     try {>>"%PS%"
echo         [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12>>"%PS%"
echo         Invoke-WebRequest -Uri $GIT_URL -OutFile $tmp -UseBasicParsing>>"%PS%"
echo         INFO 'Installing Git silently...'>>"%PS%"
echo         Start-Process $tmp -ArgumentList '/VERYSILENT /NORESTART /NOCANCEL /SP-' -Wait>>"%PS%"
echo         $env:PATH = [System.Environment]::GetEnvironmentVariable('PATH','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('PATH','User')>>"%PS%"
echo         $git = Get-Command git -ErrorAction SilentlyContinue>>"%PS%"
echo         if ($git) { OK ('Git installed: ' + (& git --version)) }>>"%PS%"
echo         else { FAIL 'Git install failed. Install from https://git-scm.com and re-run.' }>>"%PS%"
echo     } catch { FAIL ('Git download failed: ' + $_.Exception.Message) }>>"%PS%"
echo } else { OK ('Git found: ' + (& git --version)) }>>"%PS%"
echo.>>"%PS%"
echo # ── STEP 2: Node.js ──────────────────────────────────────────────────────>>"%PS%"
echo Step 2 'Checking for Node.js...'>>"%PS%"
echo $env:PATH = [System.Environment]::GetEnvironmentVariable('PATH','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('PATH','User')>>"%PS%"
echo $node = Get-Command node -ErrorAction SilentlyContinue>>"%PS%"
echo if (-not $node) {>>"%PS%"
echo     WARN 'Node.js not found. Downloading Node.js v20 LTS (~30 MB)...'>>"%PS%"
echo     $tmp = Join-Path $env:TEMP 'node-setup.msi'>>"%PS%"
echo     $installed = $false>>"%PS%"
echo     # Method 1: Try winget (Windows 11 / updated Windows 10)>>"%PS%"
echo     $wg = Get-Command winget -ErrorAction SilentlyContinue>>"%PS%"
echo     if ($wg) {>>"%PS%"
echo         INFO 'Trying winget install...'>>"%PS%"
echo         try {>>"%PS%"
echo             $p = Start-Process winget -ArgumentList 'install --id OpenJS.NodeJS.LTS --accept-source-agreements --accept-package-agreements --silent' -Wait -PassThru -NoNewWindow>>"%PS%"
echo             if ($p.ExitCode -eq 0) {>>"%PS%"
echo                 $env:PATH = [System.Environment]::GetEnvironmentVariable('PATH','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('PATH','User')>>"%PS%"
echo                 $node = Get-Command node -ErrorAction SilentlyContinue>>"%PS%"
echo                 if ($node) { $installed = $true; OK ('Node.js installed via winget: ' + (& node --version)) }>>"%PS%"
echo             }>>"%PS%"
echo         } catch { INFO 'winget failed, trying MSI download...' }>>"%PS%"
echo     }>>"%PS%"
echo     # Method 2: Download MSI directly>>"%PS%"
echo     if (-not $installed) {>>"%PS%"
echo         INFO 'Downloading Node.js MSI installer (~30 MB)...'>>"%PS%"
echo         try {>>"%PS%"
echo             [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12>>"%PS%"
echo             $wc = New-Object System.Net.WebClient>>"%PS%"
echo             $wc.DownloadFile($NODE_MSI, $tmp)>>"%PS%"
echo             INFO 'Installing Node.js...'>>"%PS%"
echo             $p = Start-Process msiexec.exe -ArgumentList "/i `"$tmp`" /quiet /norestart ADDLOCAL=ALL" -Wait -PassThru -Verb RunAs>>"%PS%"
echo             INFO ('MSI exit code: ' + $p.ExitCode)>>"%PS%"
echo             $env:PATH = [System.Environment]::GetEnvironmentVariable('PATH','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('PATH','User')>>"%PS%"
echo             $node = Get-Command node -ErrorAction SilentlyContinue>>"%PS%"
echo             if ($node) { $installed = $true; OK ('Node.js installed: ' + (& node --version)) }>>"%PS%"
echo         } catch { INFO ('MSI download error: ' + $_.Exception.Message) }>>"%PS%"
echo     }>>"%PS%"
echo     if (-not $installed) {>>"%PS%"
echo         Write-Host ''>>"%PS%"
echo         Write-Host '  [!!] Automatic Node.js install failed.' -ForegroundColor Yellow>>"%PS%"
echo         Write-Host '  Please install Node.js manually:' -ForegroundColor White>>"%PS%"
echo         Write-Host '  1. Open this link: https://nodejs.org/en/download' -ForegroundColor Cyan>>"%PS%"
echo         Write-Host '  2. Download the Windows Installer (.msi) LTS version' -ForegroundColor Cyan>>"%PS%"
echo         Write-Host '  3. Run the installer, click Next through all steps' -ForegroundColor Cyan>>"%PS%"
echo         Write-Host '  4. Restart your PC' -ForegroundColor Cyan>>"%PS%"
echo         Write-Host '  5. Run JARVIS-Install.bat again' -ForegroundColor Cyan>>"%PS%"
echo         Write-Host ''>>"%PS%"
echo         Start-Process 'https://nodejs.org/en/download'>>"%PS%"
echo         Write-Host '  (Opening nodejs.org in your browser...)' -ForegroundColor Gray>>"%PS%"
echo         Write-Host ''>>"%PS%"
echo         Write-Host '  Press Enter to exit...' -ForegroundColor DarkGray>>"%PS%"
echo         Read-Host>>"%PS%"
echo         exit 1>>"%PS%"
echo     }>>"%PS%"
echo } else { OK ('Node.js found: ' + (& node --version)) }>>"%PS%"
echo.>>"%PS%"
echo # ── STEP 3: Clone / Update ───────────────────────────────────────────────>>"%PS%"
echo Step 3 'Downloading JARVIS files...'>>"%PS%"
echo if (Test-Path (Join-Path $INSTALL_DIR '.git')) {>>"%PS%"
echo     INFO 'JARVIS already installed. Pulling latest update...'>>"%PS%"
echo     Set-Location $INSTALL_DIR>>"%PS%"
echo     try {>>"%PS%"
echo         & git fetch --all>>"%PS%"
echo         & git reset --hard origin/main>>"%PS%"
echo         OK 'JARVIS updated to latest version!'>>"%PS%"
echo     } catch { WARN 'Update failed, continuing with existing files.' }>>"%PS%"
echo } else {>>"%PS%"
echo     if (Test-Path $INSTALL_DIR) { Remove-Item $INSTALL_DIR -Recurse -Force }>>"%PS%"
echo     INFO ('Cloning from GitHub to ' + $INSTALL_DIR + '...')>>"%PS%"
echo     try {>>"%PS%"
echo         & git clone $REPO $INSTALL_DIR>>"%PS%"
echo         OK 'JARVIS files downloaded!'>>"%PS%"
echo     } catch { FAIL ('Download failed: ' + $_.Exception.Message) }>>"%PS%"
echo }>>"%PS%"
echo.>>"%PS%"
echo # ── STEP 4: npm install ──────────────────────────────────────────────────>>"%PS%"
echo Step 4 'Installing dependencies (1-2 min first time)...'>>"%PS%"
echo Set-Location $INSTALL_DIR>>"%PS%"
echo $env:PATH = [System.Environment]::GetEnvironmentVariable('PATH','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('PATH','User')>>"%PS%"
echo & npm install --no-fund --no-audit>>"%PS%"
echo $npmExit = $LASTEXITCODE>>"%PS%"
echo if ($npmExit -ne 0) { FAIL 'npm install failed. Check the output above.' }>>"%PS%"
echo OK 'All dependencies installed!'>>"%PS%"
echo.>>"%PS%"
echo # ── STEP 5: Voice ────────────────────────────────────────────────────────>>"%PS%"
echo Step 5 'Installing JARVIS voice (Microsoft George British voice)...'>>"%PS%"
echo try {>>"%PS%"
echo   $voiceInstalled = $false>>"%PS%"
echo   $voices = (New-Object -ComObject SAPI.SpVoice).GetVoices()>>"%PS%"
echo   foreach ($v in $voices) { if ($v.GetDescription() -like '*George*') { $voiceInstalled = $true } }>>"%PS%"
echo   if (-not $voiceInstalled) {>>"%PS%"
echo     Write-Host '  Installing Microsoft George British voice...' -ForegroundColor Cyan>>"%PS%"
echo     $langPkg = Get-WindowsCapability -Online ^| Where-Object { $_.Name -like '*Language.Speech*en-GB*' }>>"%PS%"
echo     if ($langPkg -and $langPkg.State -ne 'Installed') {>>"%PS%"
echo       Add-WindowsCapability -Online -Name $langPkg.Name -ErrorAction SilentlyContinue>>"%PS%"
echo       Write-Host '  British voice package installed!' -ForegroundColor Green>>"%PS%"
echo     } else {>>"%PS%"
echo       Write-Host '  British voice already available.' -ForegroundColor Gray>>"%PS%"
echo     }>>"%PS%"
echo   } else {>>"%PS%"
echo     Write-Host '  Microsoft George voice already installed.' -ForegroundColor Green>>"%PS%"
echo   }>>"%PS%"
echo } catch {>>"%PS%"
echo   Write-Host '  Voice install skipped (non-critical).' -ForegroundColor Gray>>"%PS%"
echo }>>"%PS%"
echo OK 'Voice setup complete!'>>"%PS%"
echo.>>"%PS%"
echo # ── STEP 6: Shortcuts ────────────────────────────────────────────────────>>"%PS%"
echo Step 6 'Creating shortcuts...'>>"%PS%"
echo $vbs = Join-Path $INSTALL_DIR 'JARVIS.vbs'>>"%PS%"
echo $nl = [System.Environment]::NewLine>>"%PS%"
echo $vbsText  = 'Set WS = CreateObject("WScript.Shell")' + $nl>>"%PS%"
echo $vbsText += 'WS.CurrentDirectory = "' + $INSTALL_DIR + '"' + $nl>>"%PS%"
echo $vbsText += 'WS.Run "cmd /c node_modules\.bin\electron.cmd . --no-sandbox", 0, False' + $nl>>"%PS%"
echo $vbsText += 'Set WS = Nothing'>>"%PS%"
echo $asciiBytes = [System.Text.Encoding]::ASCII.GetBytes($vbsText)>>"%PS%"
echo [System.IO.File]::WriteAllBytes($vbs, $asciiBytes)>>"%PS%"
echo.>>"%PS%"
echo $desktop = [Environment]::GetFolderPath('Desktop')>>"%PS%"
echo $wshell = New-Object -ComObject WScript.Shell>>"%PS%"
echo $sc = $wshell.CreateShortcut((Join-Path $desktop 'JARVIS.lnk'))>>"%PS%"
echo $sc.TargetPath       = 'wscript.exe'>>"%PS%"
echo $sc.Arguments        = '"' + $vbs + '"'>>"%PS%"
echo $sc.WorkingDirectory = $INSTALL_DIR>>"%PS%"
echo $sc.Description      = 'JARVIS AI Desktop Assistant'>>"%PS%"
echo $ico = Join-Path $INSTALL_DIR 'assets\icons\jarvis.ico'>>"%PS%"
echo if (Test-Path $ico) { $sc.IconLocation = $ico }>>"%PS%"
echo $sc.Save()>>"%PS%"
echo.>>"%PS%"
echo $sm = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'>>"%PS%"
echo $sc2 = $wshell.CreateShortcut((Join-Path $sm 'JARVIS.lnk'))>>"%PS%"
echo $sc2.TargetPath       = 'wscript.exe'>>"%PS%"
echo $sc2.Arguments        = '"' + $vbs + '"'>>"%PS%"
echo $sc2.WorkingDirectory = $INSTALL_DIR>>"%PS%"
echo $sc2.Description      = 'JARVIS AI Desktop Assistant'>>"%PS%"
echo if (Test-Path $ico) { $sc2.IconLocation = $ico }>>"%PS%"
echo $sc2.Save()>>"%PS%"
echo.>>"%PS%"
echo OK 'Desktop shortcut created!'>>"%PS%"
echo OK 'Start Menu entry created!'>>"%PS%"
echo.>>"%PS%"
echo Write-Host ''>>"%PS%"
echo Write-Host '  ============================================================' -ForegroundColor Green>>"%PS%"
echo Write-Host '   JARVIS INSTALLATION COMPLETE!' -ForegroundColor Green>>"%PS%"
echo Write-Host '  ============================================================' -ForegroundColor Green>>"%PS%"
echo Write-Host ''>>"%PS%"
echo Write-Host "   Installed to: $INSTALL_DIR" -ForegroundColor Cyan>>"%PS%"
echo Write-Host ''>>"%PS%"
echo Write-Host '   HOW TO LAUNCH JARVIS:' -ForegroundColor White>>"%PS%"
echo Write-Host '   - Double-click JARVIS on your Desktop' -ForegroundColor Cyan>>"%PS%"
echo Write-Host '   - Search JARVIS in the Start Menu' -ForegroundColor Cyan>>"%PS%"
echo Write-Host '   - Hotkey: Alt+J (once running)' -ForegroundColor Cyan>>"%PS%"
echo Write-Host ''>>"%PS%"
echo Write-Host '   TIP: Add your API key in Settings for full AI chat!' -ForegroundColor Yellow>>"%PS%"
echo Write-Host ''>>"%PS%"
echo.>>"%PS%"
echo $ans = Read-Host '  Launch JARVIS now? (Y/N)'>>"%PS%"
echo if ($ans -match '^^[Yy]') {>>"%PS%"
echo     Write-Host '  Launching JARVIS...' -ForegroundColor Cyan>>"%PS%"
echo     Start-Process 'wscript.exe' -ArgumentList ('"' + $vbs + '"')>>"%PS%"
echo     Write-Host '  JARVIS is starting! Check your taskbar.' -ForegroundColor Green>>"%PS%"
echo }>>"%PS%"
echo.>>"%PS%"
echo Write-Host ''>>"%PS%"
echo Write-Host '  Press any key to close this installer...' -ForegroundColor DarkGray>>"%PS%"
echo $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')>>"%PS%"
endlocal
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%PS%"
set "RES=%ERRORLEVEL%"
if exist "%PS%" del /f /q "%PS%"
if "%RES%" NEQ "0" (
  echo.
  echo   Installation failed. See error above.
  pause
)
