@echo off
title JARVIS Installer
color 0B

:: J.A.R.V.I.S. ONE-FILE INSTALLER
:: Double-click this file on any Windows PC.

set "PS=%TEMP%\jarvis_%RANDOM%.ps1"
setlocal DisableDelayedExpansion

echo $ErrorActionPreference = 'Stop'>>"%PS%"
echo $ProgressPreference = 'SilentlyContinue'>>"%PS%"
echo $Host.UI.RawUI.WindowTitle = 'JARVIS Installer'>>"%PS%"
echo.>>"%PS%"
echo $INSTALL_DIR = Join-Path $env:USERPROFILE 'JARVIS'>>"%PS%"
echo $REPO        = 'https://github.com/mercy1234544/jarvis-ai.git'>>"%PS%"
echo $NODE_URL    = 'https://nodejs.org/dist/v20.11.1/node-v20.11.1-x64.msi'>>"%PS%"
echo $GIT_URL     = 'https://github.com/git-for-windows/git/releases/download/v2.44.0.windows.1/Git-2.44.0-64-bit.exe'>>"%PS%"
echo.>>"%PS%"
echo function Banner {>>"%PS%"
echo     Clear-Host>>"%PS%"
echo     Write-Host ''>>"%PS%"
echo     Write-Host '  ============================================================' -ForegroundColor Cyan>>"%PS%"
echo     Write-Host '   J.A.R.V.I.S.  -  Just A Rather Very Intelligent System' -ForegroundColor Cyan>>"%PS%"
echo     Write-Host '   One-File Installer' -ForegroundColor Cyan>>"%PS%"
echo     Write-Host '  ============================================================' -ForegroundColor Cyan>>"%PS%"
echo     Write-Host ''>>"%PS%"
echo }>>"%PS%"
echo function Step { param($n,$t) Write-Host "  [$n/5] $t" -ForegroundColor Cyan }>>"%PS%"
echo function OK   { param($t)    Write-Host "  [OK]  $t"  -ForegroundColor Green }>>"%PS%"
echo function WARN { param($t)    Write-Host "  [!!]  $t"  -ForegroundColor Yellow }>>"%PS%"
echo function INFO { param($t)    Write-Host "        $t"  -ForegroundColor DarkCyan }>>"%PS%"
echo function FAIL { param($t)    Write-Host "  [XX]  $t"  -ForegroundColor Red; Read-Host 'Press Enter to exit'; exit 1 }>>"%PS%"
echo.>>"%PS%"
echo Banner>>"%PS%"
echo.>>"%PS%"
echo Step 1 'Checking for Git...'>>"%PS%"
echo $git = Get-Command git -ErrorAction SilentlyContinue>>"%PS%"
echo if (-not $git) {>>"%PS%"
echo     WARN 'Git not found. Downloading Git for Windows (~50 MB)...'>>"%PS%"
echo     $tmp = Join-Path $env:TEMP 'git-setup.exe'>>"%PS%"
echo     try {>>"%PS%"
echo         Invoke-WebRequest -Uri $GIT_URL -OutFile $tmp -UseBasicParsing>>"%PS%"
echo         INFO 'Installing Git silently...'>>"%PS%"
echo         Start-Process $tmp -ArgumentList '/VERYSILENT /NORESTART /NOCANCEL /SP-' -Wait -NoNewWindow>>"%PS%"
echo         Remove-Item $tmp -Force -ErrorAction SilentlyContinue>>"%PS%"
echo         $env:Path = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path','User')>>"%PS%"
echo         $git = Get-Command git -ErrorAction SilentlyContinue>>"%PS%"
echo         if ($git) { OK ('Git installed: ' + (^& git --version)) }>>"%PS%"
echo         else { FAIL 'Git install failed. Install from https://git-scm.com and re-run.' }>>"%PS%"
echo     } catch { FAIL ('Git download failed: ' + $_.Exception.Message) }>>"%PS%"
echo } else { OK ('Git found: ' + (^& git --version)) }>>"%PS%"
echo.>>"%PS%"
echo Step 2 'Checking for Node.js...'>>"%PS%"
echo $node = Get-Command node -ErrorAction SilentlyContinue>>"%PS%"
echo if (-not $node) {>>"%PS%"
echo     WARN 'Node.js not found. Downloading Node.js v20 LTS (~30 MB)...'>>"%PS%"
echo     $tmp = Join-Path $env:TEMP 'node-setup.msi'>>"%PS%"
echo     try {>>"%PS%"
echo         Invoke-WebRequest -Uri $NODE_URL -OutFile $tmp -UseBasicParsing>>"%PS%"
echo         INFO 'Installing Node.js silently...'>>"%PS%"
echo         $msiArgs = '/i "' + $tmp + '" /quiet /norestart'>>"%PS%"
echo         Start-Process msiexec.exe -ArgumentList $msiArgs -Wait -NoNewWindow>>"%PS%"
echo         Remove-Item $tmp -Force -ErrorAction SilentlyContinue>>"%PS%"
echo         $env:Path = [System.Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [System.Environment]::GetEnvironmentVariable('Path','User')>>"%PS%"
echo         $node = Get-Command node -ErrorAction SilentlyContinue>>"%PS%"
echo         if ($node) { OK ('Node.js installed: ' + (^& node --version)) }>>"%PS%"
echo         else { FAIL 'Node.js install failed. Install from https://nodejs.org and re-run.' }>>"%PS%"
echo     } catch { FAIL ('Node.js download failed: ' + $_.Exception.Message) }>>"%PS%"
echo } else { OK ('Node.js found: ' + (^& node --version)) }>>"%PS%"
echo.>>"%PS%"
echo Step 3 'Downloading JARVIS files...'>>"%PS%"
echo if (Test-Path (Join-Path $INSTALL_DIR '.git')) {>>"%PS%"
echo     INFO 'JARVIS already installed. Pulling latest update...'>>"%PS%"
echo     Set-Location $INSTALL_DIR>>"%PS%"
echo     $ErrorActionPreference = 'Continue'>>"%PS%"
echo     ^& git pull origin main --ff-only>>"%PS%"
echo     $ErrorActionPreference = 'Stop'>>"%PS%"
echo     OK 'JARVIS updated to latest version!'>>"%PS%"
echo } else {>>"%PS%"
echo     if (Test-Path $INSTALL_DIR) { Remove-Item $INSTALL_DIR -Recurse -Force }>>"%PS%"
echo     INFO "Cloning to: $INSTALL_DIR">>"%PS%"
echo     $ErrorActionPreference = 'Continue'>>"%PS%"
echo     ^& git clone $REPO $INSTALL_DIR>>"%PS%"
echo     $cloneExit = $LASTEXITCODE>>"%PS%"
echo     $ErrorActionPreference = 'Stop'>>"%PS%"
echo     if ($cloneExit -ne 0) { FAIL 'Clone failed. Check your internet connection.' }>>"%PS%"
echo     OK 'JARVIS files downloaded!'>>"%PS%"
echo     Set-Location $INSTALL_DIR>>"%PS%"
echo }>>"%PS%"
echo.>>"%PS%"
echo Step 4 'Installing dependencies (1-2 min first time)...'>>"%PS%"
echo Set-Location $INSTALL_DIR>>"%PS%"
echo $ErrorActionPreference = 'Continue'>>"%PS%"
echo ^& npm install --no-fund --no-audit>>"%PS%"
echo $npmExit = $LASTEXITCODE>>"%PS%"
echo $ErrorActionPreference = 'Stop'>>"%PS%"
echo if ($npmExit -ne 0) { FAIL 'npm install failed. Check the output above.' }>>"%PS%"
echo OK 'All dependencies installed!'>>"%PS%"
echo.>>"%PS%"
echo Step 5 'Creating shortcuts...'>>"%PS%"
echo $vbs = Join-Path $INSTALL_DIR 'JARVIS.vbs'>>"%PS%"
echo $nl = [System.Environment]::NewLine>>"%PS%"
echo $vbsText  = 'Set WS = CreateObject("WScript.Shell")' + $nl>>"%PS%"
echo $vbsText += 'WS.CurrentDirectory = "' + $INSTALL_DIR + '"' + $nl>>"%PS%"
echo $vbsText += 'WS.Run "cmd /c node_modules\.bin\electron.cmd . --no-sandbox", 0, False' + $nl>>"%PS%"
echo $vbsText += 'Set WS = Nothing'>>"%PS%"
echo $asciiBytes = [System.Text.Encoding]::ASCII.GetBytes($vbsText)>>"%PS%"
echo [System.IO.File]::WriteAllBytes($vbs, $asciiBytes)>>"%PS%"
echo.>>"%PS%"
echo $desktop = [Environment]::GetFolderPath('Desktop')>>"%PS%"
echo $wshell = New-Object -ComObject WScript.Shell>>"%PS%"
echo $sc = $wshell.CreateShortcut((Join-Path $desktop 'JARVIS.lnk'))>>"%PS%"
echo $sc.TargetPath       = 'wscript.exe'>>"%PS%"
echo $sc.Arguments        = '"' + $vbs + '"'>>"%PS%"
echo $sc.WorkingDirectory = $INSTALL_DIR>>"%PS%"
echo $sc.Description      = 'JARVIS AI Desktop Assistant'>>"%PS%"
echo $ico = Join-Path $INSTALL_DIR 'assets\icons\jarvis.ico'>>"%PS%"
echo if (Test-Path $ico) { $sc.IconLocation = $ico }>>"%PS%"
echo $sc.Save()>>"%PS%"
echo.>>"%PS%"
echo $sm = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'>>"%PS%"
echo $sc2 = $wshell.CreateShortcut((Join-Path $sm 'JARVIS.lnk'))>>"%PS%"
echo $sc2.TargetPath       = 'wscript.exe'>>"%PS%"
echo $sc2.Arguments        = '"' + $vbs + '"'>>"%PS%"
echo $sc2.WorkingDirectory = $INSTALL_DIR>>"%PS%"
echo $sc2.Description      = 'JARVIS AI Desktop Assistant'>>"%PS%"
echo if (Test-Path $ico) { $sc2.IconLocation = $ico }>>"%PS%"
echo $sc2.Save()>>"%PS%"
echo.>>"%PS%"
echo OK 'Desktop shortcut created!'>>"%PS%"
echo OK 'Start Menu entry created!'>>"%PS%"
echo.>>"%PS%"
echo Write-Host ''>>"%PS%"
echo Write-Host '  ============================================================' -ForegroundColor Green>>"%PS%"
echo Write-Host '   JARVIS INSTALLATION COMPLETE!' -ForegroundColor Green>>"%PS%"
echo Write-Host '  ============================================================' -ForegroundColor Green>>"%PS%"
echo Write-Host ''>>"%PS%"
echo Write-Host "   Installed to: $INSTALL_DIR" -ForegroundColor Cyan>>"%PS%"
echo Write-Host ''>>"%PS%"
echo Write-Host '   HOW TO LAUNCH JARVIS:' -ForegroundColor White>>"%PS%"
echo Write-Host '   - Double-click JARVIS on your Desktop' -ForegroundColor Cyan>>"%PS%"
echo Write-Host '   - Search JARVIS in the Start Menu' -ForegroundColor Cyan>>"%PS%"
echo Write-Host '   - Hotkey: Alt+J (once running)' -ForegroundColor Cyan>>"%PS%"
echo Write-Host ''>>"%PS%"
echo Write-Host '   TIP: Add your OpenAI API key in Settings for full AI chat!' -ForegroundColor Yellow>>"%PS%"
echo Write-Host ''>>"%PS%"
echo.>>"%PS%"
echo $ans = Read-Host '  Launch JARVIS now? (Y/N)'>>"%PS%"
echo if ($ans -match '^^[Yy]') {>>"%PS%"
echo     Write-Host '  Launching JARVIS...' -ForegroundColor Cyan>>"%PS%"
echo     Start-Process 'wscript.exe' -ArgumentList ('"' + $vbs + '"')>>"%PS%"
echo     Write-Host '  JARVIS is starting! Check your taskbar.' -ForegroundColor Green>>"%PS%"
echo }>>"%PS%"
echo.>>"%PS%"
echo Write-Host ''>>"%PS%"
echo Write-Host '  Press any key to close this installer...' -ForegroundColor DarkGray>>"%PS%"
echo $null = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')>>"%PS%"

endlocal

powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%PS%"
set "RES=%ERRORLEVEL%"
if exist "%PS%" del /f /q "%PS%"

if "%RES%" NEQ "0" (
  echo.
  echo   Installation failed. See error above.
  pause
)
